name: Publish release

on:
  release:
    types: [published]

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8

      - name: Setup build cache
        uses: actions/cache@v2.1.6
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Update versioning
        run: |
          NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          sed -E -e 's|mod_version=.+|mod_version='$NEW_VERSION'|g' -i build.properties
          sed -E -e 's|final val Version: String = ".+"|final val Version: String = "'$NEW_VERSION'"|g' -i src/main/scala/com/github/jtrim777/scalacore/ScalaCore.scala
          sed -E -e 's|"version" : ".+"|"version" : "'$NEW_VERSION'"|g' -i src/main/resources/mcmod.info
          sed -E -e 's|version=".+" #mod|version="'$NEW_VERSION'" #mod|g' -i src/main/resources/META-INF/mods.toml

      - name: Commit version update
        run: |
          NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          git pull github ${GITHUB_REF} --ff-only
          git config user.name "GitHub Actions"
          git config user.email "jtrimble777@gmeil.com"
          git add .
          git commit -m "Update versioning info"
          git tag --force 'v'$NEW_VERSION
          git push -u origin master


      - name: Publish artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        # The GITHUB_REF tag comes in the format 'refs/tags/xxx'.
        # So if we split on '/' and take the 3rd value, we can get the release name.
        run: |
          NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          echo "New version: ${NEW_VERSION}"
          echo "Github username: ${GITHUB_ACTOR}"
          ./gradlew -Pversion=${NEW_VERSION} publish
